name: toptodo_topdesk_provider_api
description: Implementation for TopdeskProvider from the toptodo_data package that calls the TOPdesk API
version: 0.0.1
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  async: ^2.4.0
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 6e2a73e0a55d2d6d359f04f8ecaef6bd72774535

dev_dependencies:
  test: ^1.11.0
  test_coverage: ^0.4.0
  