name: toptodo_topdesk_provider_api
description: Implementation for TopdeskProvider from the toptodo_data package that calls the TOPdesk API
version: 0.0.1
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 3226a77d7019745fbe2c93a3c3a0fb30cb1e803c

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  