name: toptodo
description: App to quickly create a new incident in TOPdesk as a todo item
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

version: 0.0.1

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1
  meta: ^1.1.7
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 8c7d41988c104c16c976f21d192513820916ae13
  toptodo_repository_providers_impl:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_repository_providers_impl
      ref: 8c0301b132ffc155583dc9f09832490c3f4cd35e
  toptodo_topdesk_provider_api:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_api
      ref: 8c0301b132ffc155583dc9f09832490c3f4cd35e

dev_dependencies:
  flutter_test:
    sdk: flutter
  toptodo_topdesk_provider_mock:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_mock
      ref: 8c0301b132ffc155583dc9f09832490c3f4cd35e
  bloc_test: ^2.2.2
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
