name: toptodo
description: App to quickly create a new incident in TOPdesk as a todo item
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

version: 0.0.1

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1
  meta: ^1.1.7
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 4b11505bc62b67ae6a453fd13fbb669b9b2d23b2
  toptodo_repository_providers_impl:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_repository_providers_impl
      ref: 95d985645e85fa62fecdb53f9eaf2efd07e7c4a8
  toptodo_topdesk_provider_api:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_api
      ref: 95d985645e85fa62fecdb53f9eaf2efd07e7c4a8

dev_dependencies:
  flutter_test:
    sdk: flutter
  toptodo_topdesk_provider_mock:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_mock
      ref: 95d985645e85fa62fecdb53f9eaf2efd07e7c4a8
  bloc_test: ^2.2.2
  mockito: ^4.1.1

dependency_overrides:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
