name: toptodo
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^0.6.1
  flutter_bloc: ^2.0.0
  toptodo_data:
    path: packages/toptodo_data
  toptodo_repository_providers_impl:
    path: packages/toptodo_repository_providers_impl

dev_dependencies:
  flutter_test:
    sdk: flutter
  toptodo_topdesk_provider_mock:
    path: packages/toptodo_topdesk_provider_mock

flutter:

  uses-material-design: true

