name: toptodo
description: App to quickly create a new incident in TOPdesk as a todo item
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.0.1
  toptodo_data:
    path: packages/toptodo_data
  toptodo_repository_providers_impl:
    path: packages/toptodo_repository_providers_impl

dev_dependencies:
  flutter_test:
    sdk: flutter
  toptodo_topdesk_provider_mock:
    path: packages/toptodo_topdesk_provider_mock
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
