name: toptodo
description: App to quickly create a new incident in TOPdesk as a todo item
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

version: 0.0.1

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1
  meta: ^1.1.7
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: e159e06b680341b915ace7e81c68f106311cb40a
  toptodo_repository_providers_impl:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_repository_providers_impl
      ref: 3af41a03fbec25d850811e1fffbd4d622194ec81
  toptodo_topdesk_provider_api:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_api
      ref: 3af41a03fbec25d850811e1fffbd4d622194ec81

dev_dependencies:
  flutter_test:
    sdk: flutter
  toptodo_topdesk_provider_mock:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_mock
      ref: 3af41a03fbec25d850811e1fffbd4d622194ec81

flutter:
  uses-material-design: true

  assets:
    - assets/
