name: toptodo
description: App to quickly create a new incident in TOPdesk as a todo item
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

version: 0.0.1

environment:
  sdk: ">=2.6.1 <3.0.0"

# For internal toptodo packages a git repo is used instead of a relative path
# because of this issue: https://github.com/dart-lang/pub/issues/950

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.0.1
  flutter_bloc: ^3.1.0
  meta: ^1.1.8
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 973e90fb7863e8c50546c376ab7be67498cadb3c
  toptodo_repository_providers_impl:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_repository_providers_impl
      ref: 894615a83a218fc388ad453618d22987a65f9d5e
  toptodo_topdesk_provider_api:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_api
      ref: 894615a83a218fc388ad453618d22987a65f9d5e
  url_launcher: ^5.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^3.0.0
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9
  mockito: ^4.1.1
  toptodo_topdesk_provider_mock:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_mock
      ref: 894615a83a218fc388ad453618d22987a65f9d5e

# used to override flutter_test that uses an older version
dependency_overrides:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: BreeSerif
      fonts:
        - asset: fonts/BreeSerif-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "scripts/images/logo.png"

flutter_native_splash:
  color: "E0F1E6"
