name: toptodo
description: App to quickly create a new incident in TOPdesk as a todo item
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

version: 0.0.1

environment:
  sdk: ">=2.6.1 <3.0.0"


# For internal toptodo packages a git repo is used instead of a relative path
# because of this issue: https://github.com/dart-lang/pub/issues/950

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  equatable: ^1.0.1
  flutter_bloc: ^3.1.0
  meta: ^1.1.8
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 70131ea6133de0293d59e244e9dc5fb1068e0bc1
  toptodo_repository_providers_impl:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_repository_providers_impl
      ref: 0ca5444a4c068ba5063e592fa1fa0aaa40a0f883
  toptodo_topdesk_provider_api:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_api
      ref: 0ca5444a4c068ba5063e592fa1fa0aaa40a0f883

dev_dependencies:
  flutter_test:
    sdk: flutter
  toptodo_topdesk_provider_mock:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_mock
      ref: 0ca5444a4c068ba5063e592fa1fa0aaa40a0f883
  bloc_test: ^3.0.0
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9

# used to override flutter_test that uses an older version
dependency_overrides:
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "scripts/images/logo.png"

flutter_native_splash:
  color: "E0F1E6"
