name: toptodo
description: App to quickly create a new incident in TOPdesk as a todo item
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

version: 0.0.1

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  flutter_bloc: ^2.1.1
  meta: ^1.1.7
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: a5969b67f3213322d87554e41c0d1db734df01f2
  toptodo_repository_providers_impl:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_repository_providers_impl
      ref: dafaecbb50105d371b026b0a78d22c6a8ae7b236
  toptodo_topdesk_provider_api:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_api
      ref: dafaecbb50105d371b026b0a78d22c6a8ae7b236

dev_dependencies:
  flutter_test:
    sdk: flutter
  toptodo_topdesk_provider_mock:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_provider_mock
      ref: dafaecbb50105d371b026b0a78d22c6a8ae7b236

flutter:
  uses-material-design: true

  assets:
    - assets/
