name: toptodo_backend
description: A backend that mocks a TOPdesk server
version: 0.0.1
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  toptodo_data:
    git:
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 30a48a1b28dabfebf7251bfd589db7cc0f048653
  toptodo_topdesk_test_data:
    git:
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_test_data
      ref: 9ecf2dceb7691aaa71a0a73848f31eed5290532a

dev_dependencies:
  mock_request: ^1.0.6
  test: ^1.11.1
  test_coverage: ^0.4.1
  toptodo_topdesk_api:
    git:
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_topdesk_api
      ref: 9ecf2dceb7691aaa71a0a73848f31eed5290532a
