name: toptodo_topdesk_provider_mock
description: Mock implementation for TopdeskProvider from the toptodo_data package
version: 0.0.1
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toptodo_data:
    git: 
      url: git://github.com/bennorichters/toptodo
      path: packages/toptodo_data
      ref: 30950d3ab2c0aabe72242f6ea9892ea28e163519

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - json/
