name: toptodo_data
description: Data layer for TOPtodo
version: 0.0.1
author: Benno Richters <b.richters@gmail.com>
repository: https://github.com/bennorichters/toptodo/
issue_tracker: https://github.com/bennorichters/toptodo/issues
homepage: https://github.com/bennorichters/toptodo/

environment:
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  equatable: ^1.0.1

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
